Add multiple python version with python 3.6 afterwards in travis ci
avocado-framework/avocado-vt pull request #2797
Opened 2020-10-23 07:04 UTC by chunfuwen

Remove allow_failures for python 3+, and add more disable lint items to allow travis test pass

Signed-off-by: chunfuwen <chwen@redhat.com>

2020-10-23 09:40 UTC, pevogam approved these changes
Thank you for this @chunfuwen! I guess my only concern reviewing this is that most of the disabled pylint checks are from the error class. Are there any of them that are easy to fix or spotted at just a few locations? Can we mark resolving the disabled errors as a task by for instance, opening an issue about it?

2020-10-23 13:43 UTC, chunfuwen commented
Sound like there are quite number of errors if no addition disable items added. Not sure whether contributors would like to fix them, see https://travis-ci.org/github/avocado-framework/avocado-vt/jobs/737935974
*********************************************************************************************************************************************
inspekt checkall --disable-lint W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,W605 --disable-style W605,W606,E501,E265,W601,E402,E722,E741 --exclude avocado-libs --no-license-check
PEP8 disabled: W605,W606,E501,E265,W601,E402,E722,E741
Pylint disabled: W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,W605
Pylint enabled : W0611
License check: disabled
************* Module avocado-vt.selftests.unit.test_propcan
E0001:276,0: : invalid syntax (<unknown>, line 276)
************* Module avocado-vt.selftests.unit.test_qemu_devices
E1111:796,8: Container.test_qdev_functional: Assigning result of a function call, where the function has no return
E1111:805,8: Container.test_qdev_functional: Assigning result of a function call, where the function has no return
************* Module cache_populate
E0611:  7,0: : No name 'Github' in module 'github'
************* Module label_issues
E0611:  6,0: : No name 'Github' in module 'github'
************* Module example
E0611:  9,0: : No name 'Github' in module 'github'
************* Module pulls_applied
E0611:  7,0: : No name 'Github' in module 'github'
************* Module unassigned_issues
E0611:  6,0: : No name 'Github' in module 'github'
************* Module stale_pulls
E0611:  7,0: : No name 'Github' in module 'github'
************* Module avocado-vt.virttest.qemu_storage
E1135:1623,30: QemuImg.dd: Value 'meta' doesn't support membership test
E1137:1625,12: QemuImg.dd: 'meta' does not support item assignment
************* Module avocado-vt.virttest.propcan
E1133:292,19: PropCan.__len__: Non-iterable value self.__all_slots__ is used in an iterating context
E1133:317,31: PropCan.keys: Non-iterable value self.__all_slots__ is used in an iterating context
************* Module avocado-vt.virttest.utils_net
I1101:3457,14: get_ip_address_by_interface: Module 'netifaces' has no 'AF_INET6' member, but source is unavailable. Consider adding this module to extension-pkg-whitelist if you want to perform analysis based on run-time introspection of living objects.
I1101:3460,14: get_ip_address_by_interface: Module 'netifaces' has no 'AF_INET' member, but source is unavailable. Consider adding this module to extension-pkg-whitelist if you want to perform analysis based on run-time introspection of living objects.
I1101:3462,11: get_ip_address_by_interface: Module 'netifaces' has no 'ifaddresses' member, but source is unavailable. Consider adding this module to extension-pkg-whitelist if you want to perform analysis based on run-time introspection of living objects.
************* Module avocado-vt.virttest.graphical_console
E1136:483,25: QMPConsole._translate_pos_qmp: Value 'self._pointer_pos' is unsubscriptable
E1136:484,25: QMPConsole._translate_pos_qmp: Value 'self._pointer_pos' is unsubscriptable
************* Module avocado-vt.virttest.element_tree
E0301:965,8: iterparse.__iter__: __iter__ returns non-iterator
************* Module avocado-vt.virttest.staging.lv_utils
E1135:355,46: lv_revert: Value 'ex' doesn't support membership test
E1135:358,71: lv_revert: Value 'ex' doesn't support membership test
E1135:363,46: lv_revert: Value 'ex' doesn't support membership test
************* Module avocado-vt.virttest.remote_commander.remote_runner
E1111:355,12: CmdSlave.__call__: Assigning result of a function call, where the function has no return
E1111:360,12: CmdSlave.__call__: Assigning result of a function call, where the function has no return
E1111:363,12: CmdSlave.__call__: Assigning result of a function call, where the function has no return
************* Module avocado-vt.virttest.libvirt_xml.vm_xml
E1133:2519,20: VMCPUTuneXML.__init__: Non-iterable value self.__all_slots__ is used in an iterating context
************* Module avocado-vt.virttest.libvirt_xml.devices.disk
E1133:351,24: Disk.IOTune.__init__: Non-iterable value self.__all_slots__ is used in an iterating context
************* Module avocado-vt.virttest.utils_test.qemu.migration
E0633:909,16: MultihostMigrationFd._connect_to_server: Attempting to unpack a non-sequence
************* Module avocado-vt.virttest.qemu_devices.qdevices
E1111:259,16: QBaseDevice.hotplug: Assigning result of a function call, where the function has no return
E1111:289,16: QBaseDevice.unplug: Assigning result of a function call, where the function has no return
The command "inspekt checkall --disable-lint W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,W605 --disable-style W605,W606,E501,E265,W601,E402,E722,E741 --exclude avocado-libs --no-license-check" exited with 2.

2020-10-23 13:49 UTC, chunfuwen commented
Anyway, I create one issue to track them as here,https://github.com/avocado-framework/avocado-vt/issues/2799

2020-10-23 13:55 UTC, pevogam commented
> Sound like there are quite number of errors if no addition disable items added. Not sure whether contributors would like to fix them, see https://travis-ci.org/github/avocado-framework/avocado-vt/jobs/737935974
> 
> inspekt checkall --disable-lint W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,W605 --disable-style W605,W606,E501,E265,W601,E402,E722,E741 --exclude avocado-libs --no-license-check
> PEP8 disabled: W605,W606,E501,E265,W601,E402,E722,E741
> Pylint disabled: W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,W605
> Pylint enabled : W0611
> License check: disabled
> ************* Module avocado-vt.selftests.unit.test_propcan
> E0001:276,0: : invalid syntax (, line 276)
> ************* Module avocado-vt.selftests.unit.test_qemu_devices
> E1111:796,8: Container.test_qdev_functional: Assigning result of a function call, where the function has no return
> E1111:805,8: Container.test_qdev_functional: Assigning result of a function call, where the function has no return
> ************* Module cache_populate
> E0611: 7,0: : No name 'Github' in module 'github'
> ************* Module label_issues
> E0611: 6,0: : No name 'Github' in module 'github'
> ************* Module example
> E0611: 9,0: : No name 'Github' in module 'github'
> ************* Module pulls_applied
> E0611: 7,0: : No name 'Github' in module 'github'
> ************* Module unassigned_issues
> E0611: 6,0: : No name 'Github' in module 'github'
> ************* Module stale_pulls
> E0611: 7,0: : No name 'Github' in module 'github'
> ************* Module avocado-vt.virttest.qemu_storage
> E1135:1623,30: QemuImg.dd: Value 'meta' doesn't support membership test
> E1137:1625,12: QemuImg.dd: 'meta' does not support item assignment
> ************* Module avocado-vt.virttest.propcan
> E1133:292,19: PropCan.**len**: Non-iterable value self.**all_slots** is used in an iterating context
> E1133:317,31: PropCan.keys: Non-iterable value self.**all_slots** is used in an iterating context
> ************* Module avocado-vt.virttest.utils_net
> I1101:3457,14: get_ip_address_by_interface: Module 'netifaces' has no 'AF_INET6' member, but source is unavailable. Consider adding this module to extension-pkg-whitelist if you want to perform analysis based on run-time introspection of living objects.
> I1101:3460,14: get_ip_address_by_interface: Module 'netifaces' has no 'AF_INET' member, but source is unavailable. Consider adding this module to extension-pkg-whitelist if you want to perform analysis based on run-time introspection of living objects.
> I1101:3462,11: get_ip_address_by_interface: Module 'netifaces' has no 'ifaddresses' member, but source is unavailable. Consider adding this module to extension-pkg-whitelist if you want to perform analysis based on run-time introspection of living objects.
> ************* Module avocado-vt.virttest.graphical_console
> E1136:483,25: QMPConsole._translate_pos_qmp: Value 'self._pointer_pos' is unsubscriptable
> E1136:484,25: QMPConsole._translate_pos_qmp: Value 'self._pointer_pos' is unsubscriptable
> ************* Module avocado-vt.virttest.element_tree
> E0301:965,8: iterparse.**iter**: **iter** returns non-iterator
> ************* Module avocado-vt.virttest.staging.lv_utils
> E1135:355,46: lv_revert: Value 'ex' doesn't support membership test
> E1135:358,71: lv_revert: Value 'ex' doesn't support membership test
> E1135:363,46: lv_revert: Value 'ex' doesn't support membership test
> ************* Module avocado-vt.virttest.remote_commander.remote_runner
> E1111:355,12: CmdSlave.**call**: Assigning result of a function call, where the function has no return
> E1111:360,12: CmdSlave.**call**: Assigning result of a function call, where the function has no return
> E1111:363,12: CmdSlave.**call**: Assigning result of a function call, where the function has no return
> ************* Module avocado-vt.virttest.libvirt_xml.vm_xml
> E1133:2519,20: VMCPUTuneXML.**init**: Non-iterable value self.**all_slots** is used in an iterating context
> ************* Module avocado-vt.virttest.libvirt_xml.devices.disk
> E1133:351,24: Disk.IOTune.**init**: Non-iterable value self.**all_slots** is used in an iterating context
> ************* Module avocado-vt.virttest.utils_test.qemu.migration
> E0633:909,16: MultihostMigrationFd._connect_to_server: Attempting to unpack a non-sequence
> ************* Module avocado-vt.virttest.qemu_devices.qdevices
> E1111:259,16: QBaseDevice.hotplug: Assigning result of a function call, where the function has no return
> E1111:289,16: QBaseDevice.unplug: Assigning result of a function call, where the function has no return
> The command "inspekt checkall --disable-lint W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,W605 --disable-style W605,W606,E501,E265,W601,E402,E722,E741 --exclude avocado-libs --no-license-check" exited with 2.

I think it is worth it to track all issues there even as an epic issue to gradually be worked on by many of us. We can then silence the errors for now to make this PR work but did not lose information on any potential bigger problems and todos.

2020-10-28 11:40 UTC, kylazhang commented
@chunfuwen I think we can not just ignore those kinds of error as some of them are very basic for checking, like E0001 is syntex check, and E0611 for no module find check. We may need to add inline ignore check for them one by one(eg. # pylint: disable=E0611).

2020-10-28 11:40 UTC, kylazhang requested changes
please check the comments

2020-10-29 00:19 UTC, chunfuwen commented
> @chunfuwen I think we can not just ignore those kinds of error as some of them are very basic for checking, like E0001 is syntex check, and E0611 for no module find check. We may need to add inline ignore check for them one by one(eg. # pylint: disable=E0611).

that is why we create one issue to track that https://github.com/avocado-framework/avocado-vt/issues/2799. If we add inline ignore, that is workaround solution ,and not really address issue itself.

2020-10-30 02:59 UTC, chloerh reviewed
```
************* Module avocado-vt.selftests.unit.test_propcan
E0001:276,0: : invalid syntax (, line 276)
```
This error was caused by
`tmp_long = 12345L` Python version 3.6 does not support a trailing 'L'.

Agreed with @kylazhang  E0001 cannot be ignored.  And I don't think this pr should be merged before the code check errors all fixed. If we merged this one, all checking of later prs would be like trying to catch fish with not net.

I'd vote for inline comments if there's no better way to fix errors.

2020-10-30 03:02 UTC, chloerh requested changes
Please see the last comment

2020-10-30 10:06 UTC, pevogam commented
Hi @chloerh and @kylazhang, I agree with both of you but just keep in mind that @chunfuwen's contribution is already a step in the right direction and quite often contributors sign up for a task and don't expect to have to resolve a big load of follow-up tasks just because they picked the first one. This being said, some of the most fatal errors could of course be fixed. It is @chunfuwen's call.

I agree with the fact that globally disabling some critical errors could harm other contributions too so these need inline presence only, no doubt about this.

2020-10-30 14:53 UTC, clebergnu approved these changes
I agree this is a step in the right direction.

2020-11-02 01:30 UTC, chloerh commented
> Hi @chloerh and @kylazhang, I agree with both of you but just keep in mind that @chunfuwen's contribution is already a step in the right direction and quite often contributors sign up for a task and don't expect to have to resolve a big load of follow-up tasks just because they picked the first one. This being said, some of the most fatal errors could of course be fixed. It is @chunfuwen's call.
> 
> I agree with the fact that globally disabling some critical errors could harm other contributions too so these need inline presence only, no doubt about this.

@pevogam Thank you so much for explaining.
That's true. I understand if @chunfuwen not resolving all errors this pr has brought. I just worried that if it got merged, Syntax error would not be caught from all future PRs. So here is my suggestion:
1. **Remove** E0001 from ignore list first.
2. **Hold** this PR before issue #2799 got **resolved** (not have to be @chunfuwen )

How does that sound?

2020-11-03 17:18 UTC, pevogam commented
> How does that sound?

I don't think holding the PR and letting it accumulate conflicts helps the contributor or this. I agreed though that fixing one or two major errors is ok before merging. @chunfuwen Do you mind fixing E0001 as it will hide other such errors for later PR-s?

2020-11-04 01:31 UTC, chloerh commented
> > How does that sound?
> 
> I don't think holding the PR and letting it accumulate conflicts helps the contributor or this. I agreed though that fixing one or two major errors is ok before merging. @chunfuwen Do you mind fixing E0001 as it will hide other such errors for later PR-s?

How about these 2 error:
```
E0611: 7,0: : No name 'Github' in module 'github'
E0633  Attempting to unpack a non-sequence
```
IMHO, we'd better keep catching these 2 errors too.

2020-11-04 06:20 UTC, kylazhang commented
> > @chunfuwen I think we can not just ignore those kinds of error as some of them are very basic for checking, like E0001 is syntex check, and E0611 for no module find check. We may need to add inline ignore check for them one by one(eg. # pylint: disable=E0611).
> 
> that is why we create one issue to track that #2799. If we add inline ignore, that is workaround solution ,and not really address issue itself.

No, with comments inline we can also open issues to track them. The problem is that, if we ignore them, then the check for those failure will not work and in the code there will be more and more failures, and when you adding them back, it will be more hard to deal with all of them.

2020-11-05 08:13 UTC, luckyh commented
@chunfuwen @pevogam @kylazhang @chloerh @clebergnu opened https://github.com/avocado-framework/avocado-vt/pull/2814 to fix some of issues, would you please help review?

2020-11-05 08:49 UTC, luckyh commented
@chunfuwen and, there seems to be some failures although the status was PASSED, would you please help check that?
```
$ inspekt checkall --disable-lint W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,E0001,E1111,E0611,E1135,E1137,E1133,E1136,E0633,I1101 --disable-style W605,W606,E501,E265,W601,E402,E722,E741 --exclude avocado-libs --no-license-check

PEP8 disabled: W605,W606,E501,E265,W601,E402,E722,E741

Pylint disabled: W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,E0001,E1111,E0611,E1135,E1137,E1133,E1136,E0633,I1101

Pylint enabled : W0611

License check: disabled

internal error with sending report for module ['/home/travis/build/avocado-framework/avocado-vt/setup.py']

module 'isort' has no attribute 'SortImports'

internal error with sending report for module ['/home/travis/build/avocado-framework/avocado-vt/examples/tests/service.py']

module 'isort' has no attribute 'SortImports'
...
```

2020-11-09 01:25 UTC, chunfuwen commented
> @chunfuwen and, there seems to be some failures although the status was PASSED, would you please help check that?
> 
> ```
> $ inspekt checkall --disable-lint W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,E0001,E1111,E0611,E1135,E1137,E1133,E1136,E0633,I1101 --disable-style W605,W606,E501,E265,W601,E402,E722,E741 --exclude avocado-libs --no-license-check
> 
> PEP8 disabled: W605,W606,E501,E265,W601,E402,E722,E741
> 
> Pylint disabled: W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,E0001,E1111,E0611,E1135,E1137,E1133,E1136,E0633,I1101
> 
> Pylint enabled : W0611
> 
> License check: disabled
> 
> internal error with sending report for module ['/home/travis/build/avocado-framework/avocado-vt/setup.py']
> 
> module 'isort' has no attribute 'SortImports'
> 
> internal error with sending report for module ['/home/travis/build/avocado-framework/avocado-vt/examples/tests/service.py']
> 
> module 'isort' has no attribute 'SortImports'
> ...
> ```

I grep isort under avocado -vt  by :egrep -nr 'isort' *  ,
the output is nothing, it sounds like avocado-vt doesn't have any dependence on isort.
I suspend it is pylint issue itself, and one related issue was mentioned in bugzilla ,https://bugzilla.redhat.com/show_bug.cgi?id=1710356

2020-11-09 01:40 UTC, chunfuwen commented
> @chunfuwen and, there seems to be some failures although the status was PASSED, would you please help check that?
> 
> ```
> $ inspekt checkall --disable-lint W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,E0001,E1111,E0611,E1135,E1137,E1133,E1136,E0633,I1101 --disable-style W605,W606,E501,E265,W601,E402,E722,E741 --exclude avocado-libs --no-license-check
> 
> PEP8 disabled: W605,W606,E501,E265,W601,E402,E722,E741
> 
> Pylint disabled: W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,E0001,E1111,E0611,E1135,E1137,E1133,E1136,E0633,I1101
> 
> Pylint enabled : W0611
> 
> License check: disabled
> 
> internal error with sending report for module ['/home/travis/build/avocado-framework/avocado-vt/setup.py']
> 
> module 'isort' has no attribute 'SortImports'
> 
> internal error with sending report for module ['/home/travis/build/avocado-framework/avocado-vt/examples/tests/service.py']
> 
> module 'isort' has no attribute 'SortImports'
> ...
> ```

I grep isort under avocado -vt by :egrep -nr 'isort' * ,
the output is nothing, it sounds like avocado-vt doesn't have any direct dependence on isort.
I suspend it is pylint issue itself, and one related issue was mentioned in bugzilla ,https://bugzilla.redhat.com/show_bug.cgi?id=1710356.
However, under avocado project, it has dependence on isort in the file :requirements-selftests.txt:10:isort==4.3.21; python_version >= '3.6'
We may need upgrade isort to have a try.

2020-11-09 02:12 UTC, chloerh commented
@luckyh  Thank you for your quick response and great fix :+1:

2020-11-09 02:15 UTC, chloerh approved these changes
LGTM as this commit only adds checking items with python 3.6~3.8 without disabling any pylint checkpoints

2020-11-16 03:10 UTC, merged