Introduce standalone commands to list guests and archs
avocado-framework/avocado-vt pull request #2853
Opened 2020-12-08 17:49 UTC by clebergnu

The current `--vt-list-guests` and `--vt-list-archs` options to `avocado list` depend on the `avocado.core.loader`'s "extra listing" feature, which is not a great thing.

Also, users tend to want to have access to that specific information, and not that and the test list.

This is also a preparation to when the `avocado.core.loader` is removed for good (in place of the resolver).

2020-12-08 18:32 UTC, beraldoleal requested changes
Hi @clebergnu, AFAICT, this LGTM, just two non-used imports here.

2020-12-08 18:32 UTC, beraldoleal commented on avocado_vt/plugins/vt_list_archs.py
> +from avocado.core.settings import settings
settings is not used here.

2020-12-08 18:32 UTC, beraldoleal commented on avocado_vt/plugins/vt_list_archs.py
> +from virttest.compat import add_option, is_registering_settings_required
is_registering_settings_required is not used here.

2020-12-08 18:33 UTC, beraldoleal commented on avocado_vt/plugins/vt_list_guests.py
> +            settings.register_option(section, key=key, default=None,
`help_msg` could be defined inside this if.

2020-12-08 19:06 UTC, clebergnu commented
@beraldoleal FIY pushed the changes with the issues you spotted.

2020-12-09 11:59 UTC, beraldoleal approved these changes
LGTM, thanks.

2020-12-09 14:31 UTC, willianrampazzo approved these changes

2020-12-09 14:53 UTC, merged