Add emulator accessor
avocado-framework/avocado-vt pull request #2873
Opened 2020-12-29 03:06 UTC by zhijianli88

https://libvirt.org/formatdomain.html#elementsDevices
<devices>
  <emulator>/usr/lib/xen/bin/qemu-dm</emulator>
</devices>

Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>

2021-01-04 01:31 UTC, chunfuwen commented
Can you paste some validated result here?

2021-01-04 06:24 UTC, zhijianli88 commented
> Can you paste some validated result here?

Not very clear what result do you like, avocado-vt is just a framework,  this patch just introduces a helper for (tp-libvirt)[https://github.com/autotest/tp-libvirt/pull/3230]

2021-01-04 06:32 UTC, chunfuwen commented
> https://github.com/[autotest/tp-libvirt/pull/3230](https://github.com/autotest/tp-libvirt/pull/3230)

For any PR, we need test result ,which shows basic validation pass, whether the test result is unit test based ,or specific test case result assciated with this PR

2021-01-04 07:43 UTC, zhijianli88 commented
paste the result with emulator qemu-system-x86_64
```
$ sudo virsh dumpxml avocado-vt-vm1 | grep emulator
    <emulator>/usr/bin/qemu-system-x86_64</emulator>

$ sudo avocado -V run --vt-type libvirt type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.set_virtlogd.positive_test.enable_logd
JOB ID     : e54fbccc39919b5acbd15c61749648473c1f3a0b
JOB LOG    : /home/lizhijian/avocado/job-results/job-2021-01-04T15.40-e54fbcc/job.log
 (1/1) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.set_virtlogd.positive_test.enable_logd: -
PASS (85.35 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 86.33 s
```

2021-01-04 08:32 UTC, sathnaga requested changes
@zhijianli88 we do not need this change, as we could get the emulator value from xml by other means and more over it is implicit inside devices tag and not right to be added in VMXMLbase
example, you can already get to use this in your https://github.com/autotest/tp-libvirt/pull/3230 as below with out this change here:

```
# python
Python 3.9.1 (default, Dec  8 2020, 00:00:00) 
[GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from virttest.libvirt_xml.vm_xml import VMXML
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
>>> from xml.etree.ElementTree import parse
>>> vm_xml = VMXML.new_from_inactive_dumpxml("fedora")
>>> emulator_path = parse(vm_xml.get_devices(device_type='emulator')[0]['xml']).getroot().text
>>> emulator_path
'/usr/local/lib/python3.9/site-packages/virttest/bin/install_root/bin/qemu-system-ppc64'
>>> 


----

# virsh dumpxml fedora|grep emulator
    <emulator>/usr/local/lib/python3.9/site-packages/virttest/bin/install_root/bin/qemu-system-ppc64</emulator>

```

2021-01-04 08:51 UTC, zhijianli88 commented
> @zhijianli88 we do not need this change, as we could get the emulator value from xml by other means and more over it is implicit inside devices tag and not right to be added in VMXMLbase
> example, you can already get to use this in your [autotest/tp-libvirt#3230](https://github.com/autotest/tp-libvirt/pull/3230) as below with out this change here:
> 
> ```
> # python
> Python 3.9.1 (default, Dec  8 2020, 00:00:00) 
> [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from virttest.libvirt_xml.vm_xml import VMXML
> WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
> >>> from xml.etree.ElementTree import parse
> >>> vm_xml = VMXML.new_from_inactive_dumpxml("fedora")
> >>> emulator_path = parse(vm_xml.get_devices(device_type='emulator')[0]['xml']).getroot().text
> >>> emulator_path
> '/usr/local/lib/python3.9/site-packages/virttest/bin/install_root/bin/qemu-system-ppc64'
> >>> 
> 
> 
> ----
> 
> # virsh dumpxml fedora|grep emulator
>     <emulator>/usr/local/lib/python3.9/site-packages/virttest/bin/install_root/bin/qemu-system-ppc64</emulator>
> ```

Of cause, your apporach works well. Currently tp-libvirt has some other places using a hardcode qemu-kvm. so i still hope we have a wrapper(maybe in eslewhere) to get the emulator more clear so that we can replace all of them in the furture.

2021-01-08 07:48 UTC, sathnaga commented
> > @zhijianli88 we do not need this change, as we could get the emulator value from xml by other means and more over it is implicit inside devices tag and not right to be added in VMXMLbase
> > example, you can already get to use this in your [autotest/tp-libvirt#3230](https://github.com/autotest/tp-libvirt/pull/3230) as below with out this change here:
> > ```
> > # python
> > Python 3.9.1 (default, Dec  8 2020, 00:00:00) 
> > [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)] on linux
> > Type "help", "copyright", "credits" or "license" for more information.
> > >>> from virttest.libvirt_xml.vm_xml import VMXML
> > WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
> > >>> from xml.etree.ElementTree import parse
> > >>> vm_xml = VMXML.new_from_inactive_dumpxml("fedora")
> > >>> emulator_path = parse(vm_xml.get_devices(device_type='emulator')[0]['xml']).getroot().text
> > >>> emulator_path
> > '/usr/local/lib/python3.9/site-packages/virttest/bin/install_root/bin/qemu-system-ppc64'
> > >>> 
> > 
> > 
> > ----
> > 
> > # virsh dumpxml fedora|grep emulator
> >     <emulator>/usr/local/lib/python3.9/site-packages/virttest/bin/install_root/bin/qemu-system-ppc64</emulator>
> > ```
> 
> Of cause, your approach works well. Currently tp-libvirt has some other places using a hardcode qemu-kvm. so i still hope we have a wrapper(maybe in eslewhere) to get the emulator more clear so that we can replace all of them in the furture.

yes, makes sense, feel free to send a helper method.

2021-01-08 07:49 UTC, sathnaga commented
with above conversation, this PR is not needed, feel free to reopen if otherwise. thanks!

2021-01-08 07:49 UTC, closed without merging