[PoC] nrunner support
avocado-framework/avocado-vt pull request #2904
Opened 2021-01-26 18:39 UTC by clebergnu

This is a very early, and very limited, but still functional, implementation of a runner that plugs into Avocado's "nrunner" architecture.

If you're interested in trying it out, after bootstrapping Avocado-VT, you should be able to do:

```
$ avocado list --resolver boot 
avocado-vt io-github-autotest-qemu.boot
```

And to run tests:

```
$ avocado run --test-runner=nrunner boot /bin/true /bin/true /bin/true
JOB ID     : 22563e6ab3c701dfefc95b0eff5d25cabac0d6a3
JOB LOG    : /home/cleber/avocado/job-results/job-2021-01-26T13.39-22563e6/job.log
 (2/4) /bin/true: STARTED
 (3/4) /bin/true: STARTED
 (2/4) /bin/true: PASS (0.01 s)
 (3/4) /bin/true: PASS (0.01 s)
 (1/4) io-github-autotest-qemu.boot: STARTED
 (4/4) /bin/true: STARTED
 (4/4) /bin/true: PASS (0.01 s)
 (1/4) io-github-autotest-qemu.boot: PASS (20.28 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/cleber/avocado/job-results/job-2021-01-26T13.39-22563e6/results.html
JOB TIME   : 29.59 s
```

2021-01-26 18:40 UTC, clebergnu commented
@richtja @beraldoleal @willianrampazzo @pevogam I beliebe there was an issue that referenced this WiP/PoC, so I just posted it.

2021-01-26 18:42 UTC, pevogam commented
Would gladly check it out soon, thanks for the PoC!

2021-01-26 20:31 UTC, beraldoleal requested changes
Hi @clebergnu , the code looks fine to me.

Just a few comments, all easy to fix.

2021-01-26 20:31 UTC, beraldoleal commented on avocado_vt/loader.py
>  from .options import VirtTestOptionsProcess
VirtTestOptionsProcess is not being used anymore here.

2021-01-26 20:31 UTC, beraldoleal commented on avocado_vt/plugins/vt_resolver.py
> +        runnables = [self._parameters_to_runnable(_) for _ in
nitpicking: Since you are using `_`, I would like to suggest renaming this to `d` for instance.

2021-01-26 20:31 UTC, beraldoleal commented on avocado_vt/plugins/vt_runner.py
> +        t_types = params.get("type").split()
test_types?

2021-01-26 20:31 UTC, beraldoleal commented on avocado_vt/plugins/vt_runner.py
> +        subtest_dir = None
I could not find usages of this variable.

2021-01-26 20:31 UTC, beraldoleal commented on avocado_vt/discovery.py
> +        # Evaluate the proper avocado-vt test name
If you don't mind, could you please convert this to a docstring?

2021-02-01 16:04 UTC, pevogam commented
Hi @clebergnu,

> If you're interested in trying it out, after bootstrapping Avocado-VT, you should be able to do:
> 
> ```
> $ avocado list --resolver boot 
> avocado-vt io-github-autotest-qemu.boot
> ```

I am having some trouble resolving the test:

```
# avocado list --resolver boot
# avocado list boot
VT io-github-autotest-qemu.boot
# dnf list installed | grep python3-avocado
python3-avocado.noarch                       84.0-1.fc32                      @@commandline   
python3-avocado-common.noarch                84.0-1.fc32                      @@commandline   
python3-avocado-plugins-i2n.noarch           82.0-0.fc32                      @@commandline   
python3-avocado-plugins-output-html.noarch   84.0-1.fc32                      @@commandline   
python3-avocado-plugins-result-upload.noarch 84.0-1.fc32                      @@commandline   
python3-avocado-plugins-resultsdb.noarch     84.0-1.fc32                      @@commandline   
python3-avocado-plugins-vt.noarch            0.26.0-1.fc32                    @@commandline   
```
The avocado RPMs are produced from avocado-framework/avocado@9b372adeec6dceaba276ca4729f2e5a2fcccaa4c and the VT RPM is produced from clebergnu/avocado-vt@d2663377c40204636868fc07bc1b6892233c5571.

Any quick hints on where to look?

I am probably missing something obvious.

2021-02-03 10:32 UTC, richtja approved these changes
Hi @clebergnu, thanks for this. I tested it, and it works fine on my machine. Except the comments from @beraldoleal  LGTM

2021-02-03 12:07 UTC, pevogam commented
> Hi @clebergnu, thanks for this. I tested it, and it works fine on my machine. Except the comments from @beraldoleal LGTM

Hi @richtja, as you tested succesfuly do you mind providing hints about your configuration so that I can compare with what I described above?

2021-02-03 13:20 UTC, richtja commented
> > Hi @clebergnu, thanks for this. I tested it, and it works fine on my machine. Except the comments from @beraldoleal LGTM
> 
> Hi @richtja, as you tested succesfuly do you mind providing hints about your configuration so that I can compare with what I described above?

Hi @pevogam I didn't test it with RPM packages. I did it from source code in the development environment. But I don't know if it helps with your problem.

2021-02-03 13:35 UTC, clebergnu commented
> Hi @clebergnu,
> 
> > If you're interested in trying it out, after bootstrapping Avocado-VT, you should be able to do:
> > ```
> > $ avocado list --resolver boot 
> > avocado-vt io-github-autotest-qemu.boot
> > ```
> 
> I am having some trouble resolving the test:
> 
> ```
> # avocado list --resolver boot
> # avocado list boot
> VT io-github-autotest-qemu.boot
> # dnf list installed | grep python3-avocado
> python3-avocado.noarch                       84.0-1.fc32                      @@commandline   
> python3-avocado-common.noarch                84.0-1.fc32                      @@commandline   
> python3-avocado-plugins-i2n.noarch           82.0-0.fc32                      @@commandline   
> python3-avocado-plugins-output-html.noarch   84.0-1.fc32                      @@commandline   
> python3-avocado-plugins-result-upload.noarch 84.0-1.fc32                      @@commandline   
> python3-avocado-plugins-resultsdb.noarch     84.0-1.fc32                      @@commandline   
> python3-avocado-plugins-vt.noarch            0.26.0-1.fc32                    @@commandline   
> ```
> 
> The avocado RPMs are produced from [avocado-framework/avocado@9b372ad](https://github.com/avocado-framework/avocado/commit/9b372adeec6dceaba276ca4729f2e5a2fcccaa4c) and the VT RPM is produced from [clebergnu/avocado-vt@d266337](https://github.com/clebergnu/avocado-vt/commit/d2663377c40204636868fc07bc1b6892233c5571).
> 
> Any quick hints on where to look?
> 
> I am probably missing something obvious.

Hi @pevogam ,

I see that the `python3-avocado-plugins-vt.noarch            0.26.0-1.fc32` has a custom version scheme, so I wonder if you double checked that it was built from the code in this PR.

One way to check if the plugins are active, is to `avocado plugins | grep vt` and make sure the resolver plugin is shown:

```
...
vt                   Test resolver for Avocado-VT tests
```

Also, make sure that the `avocado-runner-avocado-vt` script is callable:

```
$ avocado-runner-avocado-vt --help
usage: avocado-runner-avocado-vt [-h]
                                 {capabilities,runnable-run,runnable-run-recipe,task-run,task-run-recipe}
                                 ...

nrunner application for Avocado-VT tests

positional arguments:
  {capabilities,runnable-run,runnable-run-recipe,task-run,task-run-recipe}
    capabilities        Outputs capabilities, including runnables and commands
    runnable-run        Runs a runnable definition from arguments
    runnable-run-recipe
                        Runs a runnable definition from a recipe
    task-run            Runs a task from arguments
    task-run-recipe     Runs a task from a recipe

optional arguments:
  -h, --help            show this help message and exit
```

2021-02-03 21:38 UTC, pevogam commented
Hi @cleber,

> I see that the `python3-avocado-plugins-vt.noarch 0.26.0-1.fc32` has a custom version scheme, so I wonder if you double checked that it was built from the code in this PR.

I thought you would ask about this, sorry for not explaining this right away - I cloned from `clebergnu:poc/nrunner` and it seems you don't have the version tags in your fork. The tarball is created from the master branch though, only the version number is different from the spec.

> One way to check if the plugins are active, is to `avocado plugins | grep vt` and make sure the resolver plugin is shown:
> 
> ```
> ...
> vt                   Test resolver for Avocado-VT tests
> ```
> 
> Also, make sure that the `avocado-runner-avocado-vt` script is callable:
> 
> ```
> $ avocado-runner-avocado-vt --help
> usage: avocado-runner-avocado-vt [-h]
>                                  {capabilities,runnable-run,runnable-run-recipe,task-run,task-run-recipe}
>                                  ...
> 
> nrunner application for Avocado-VT tests
> 
> positional arguments:
>   {capabilities,runnable-run,runnable-run-recipe,task-run,task-run-recipe}
>     capabilities        Outputs capabilities, including runnables and commands
>     runnable-run        Runs a runnable definition from arguments
>     runnable-run-recipe
>                         Runs a runnable definition from a recipe
>     task-run            Runs a task from arguments
>     task-run-recipe     Runs a task from a recipe
> 
> optional arguments:
>   -h, --help            show this help message and exit
> ```

Unfortunately none of these two holds in my case:
```
# avocado plugins | grep vt
vt-init       VT plugin initilization
vt-bootstrap   Avocado VT - implements the 'vt-bootstrap' subcommand
vt-list-archs  Avocado-VT 'vt-list-archs' command
vt-list-guests Avocado-VT 'vt-list-guests' command
vt             Avocado VT/virt-test support to 'run' command
vt-list        Avocado-VT/virt-test support for 'list' command
vt-joblock Avocado-VT Job Lock/Unlock
# avocado-runner-avocado-vt --help
-bash: avocado-runner-avocado-vt: command not found
```
but I guess this PoC needs needs some additional changes or entry points to work with an Avocado VT installation and my extra formalized environment might have been an overkill:

```
error: Installed (but unpackaged) file(s) found:
   /usr/bin/avocado-runner-avocado-vt
    bogus date in %changelog: Fri Jan 21 2020 Plamen Dimitrov <pdimitrov@pevogam.com> - 75.0-1
    Installed (but unpackaged) file(s) found:
   /usr/bin/avocado-runner-avocado-vt
```
(I fixed this error in my setup above by adding the file to the SPEC file but still, there must be much more to it).

Just to make sure all code is in place:
```
# ls -sh /usr/lib/python3.8/site-packages/avocado_vt/discovery.py
4.0K /usr/lib/python3.8/site-packages/avocado_vt/discovery.py
```

So I also went the way to just clone the avocado and avocado-vt repos and `make develop` but with a few changed config settings I get:


```
# avocado plugins | grep vt
Avocado crashed unexpectedly: 'Settings' object has no attribute 'get_value'
...
Avocado crashed:
Traceback (most recent call last):
  File "/root/.local/bin/avocado", line 11, in <module>
    load_entry_point('avocado-framework', 'console_scripts', 'avocado')()
  File "/usr/lib/python3.8/site-packages/avocado/core/main.py", line 75, in main
    app = AvocadoApp()
  File "/usr/lib/python3.8/site-packages/avocado/core/app.py", line 54, in __init__
    self._load_cli_plugins()
  File "/usr/lib/python3.8/site-packages/avocado/core/app.py", line 77, in _load_cli_plugins
    self._cli_dispatcher = CLIDispatcher()
  File "/usr/lib/python3.8/site-packages/avocado/core/dispatcher.py", line 36, in __init__
    super(CLIDispatcher, self).__init__('avocado.plugins.cli')
  File "/usr/lib/python3.8/site-packages/avocado/core/enabled_extension_manager.py", line 26, in __init__
    super(EnabledExtensionManager, self).__init__(namespace, invoke_kwds)
  File "/usr/lib/python3.8/site-packages/avocado/core/extension_manager.py", line 63, in __init__
    plugin = ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/avocado-vt/avocado_vt/plugins/vt.py", line 33, in <module>
    from ..loader import VirtTestLoader
  File "/root/avocado-vt/avocado_vt/loader.py", line 30, in <module>
    from virttest import storage
  File "/root/avocado-vt/virttest/storage.py", line 21, in <module>
    from virttest import iscsi
  File "/root/avocado-vt/virttest/iscsi.py", line 22, in <module>
    from virttest import utils_net
  File "/root/avocado-vt/virttest/utils_net.py", line 28, in <module>
    from virttest import openvswitch
  File "/root/avocado-vt/virttest/openvswitch.py", line 11, in <module>
    from . import utils_misc
  File "/root/avocado-vt/virttest/utils_misc.py", line 398, in <module>
    _log_file_dir = data_dir.get_tmp_dir()
  File "/root/avocado-vt/virttest/data_dir.py", line 212, in get_tmp_dir
    persistent_dir = settings.get_value('vt.common', 'tmp_dir',
AttributeError: 'Settings' object has no attribute 'get_value'
```
This is precause I have defined `vt.common.tmp_dir`.

So I will check more later I guess :/

2021-02-18 16:50 UTC, clebergnu commented
Hi @pevogam, thanks for that detail feedback!  I'll be closing this PoC version, as @richtja will pick up from this point and evolve the nrunner support (he'll most certainly take into account everything provided here).

Thanks!

2021-02-18 16:50 UTC, closed without merging

2021-02-18 17:10 UTC, pevogam commented
No worries @clebergnu, I will rerun on top of official Avocado VT release later on which might be better tested. In the meanwhile I have reported some recent Avocado VT breakage [one](https://github.com/avocado-framework/avocado-vt/commit/e8a2517b414cc70f824c6f6a796003e3c753e99b#r47013623) of which also about your recent refactoring.

@richtja I will be glad if you ping me when you open your PR as I want to be part of this feature progressing further.

2021-02-19 08:41 UTC, richtja commented
@pevogam Ok, no worries.