Make the python3 RPM the default subpackage and python2 optional
avocado-framework/avocado-vt pull request #2909
Opened 2021-01-30 15:05 UTC by pevogam

Python 2 is no longer included in the CI and slowly falling out of favor,
let's make it optional and make Python 3 the RPM package of choice.

Signed-off-by: Plamen Dimitrov <pdimitrov@pevogam.com>

2021-02-01 18:55 UTC, pevogam commented
@luckyh, @sathnaga: What is your opinion about this? Is it natural or you think it will cause someone some breakage?

2021-02-03 11:29 UTC, luckyh commented
> @luckyh, @sathnaga: What is your opinion about this? Is it natural or you think it will cause someone some breakage?

That makes sense to me, since I suppose all upstream users have already move to Python 3 now.

2021-02-16 18:58 UTC, pevogam commented
@PaulYuuu, @YongxueHong, @chloerh, @chunfuwen, what do you think about this change?

2021-02-16 19:21 UTC, clebergnu requested changes
Hi @pevogam , I like the idea, and these changes LGTM.

Could you, please, only "rebase" this patch so that the SPEC file changelog is kept in chronological and version order?  We're now at 85.0, so this would bring the version down.

Thanks!

2021-02-16 20:10 UTC, pevogam commented
> Hi @pevogam , I like the idea, and these changes LGTM.
> 
> Could you, please, only "rebase" this patch so that the SPEC file changelog is kept in chronological and version order? We're now at 85.0, so this would bring the version down.
> 
> Thanks!

Hi @clebergnu pushed with updated changelog.

The PR was originally pushed from the previous Avocado VT version (83.0) which is why it had conflicts now.

2021-02-24 09:39 UTC, sathnaga approved these changes
Makes perfect sense to me, even if any issues we should look to fix it as we encounter.

2021-02-24 09:45 UTC, YongxueHong approved these changes
It makes sense to me, LGTM.

2021-02-25 10:21 UTC, pevogam commented
ping @clebergnu

2021-02-25 23:22 UTC, clebergnu approved these changes
LGTM, thanks!

2021-02-25 23:23 UTC, merged