virttest.remote: Change default log_function for remote_login
avocado-framework/avocado-vt pull request #2984
Opened 2021-03-31 08:17 UTC by ldoktor

The old remote_login used a `utils_logfile.log_line` log_function by
default, making it convenient to set the output log file. Let's bring
back the default by changing `None` to our log function.

This can change the log_function in case people explicitly select
log_function to None but it should not matter as the function is only
used when `log_filename` is set. So the only effect would be when one
chooses to set the `log_filename` but deliberately wanted to disable
logging via the log_function, which should be very rare.

Fixes: #2822

2021-03-31 12:05 UTC, pevogam requested changes
How about my proposal in the related issue?

2021-04-28 03:51 UTC, yanan-fu commented
@ldoktor I am afraid this patch can not fix the issue. The function `login` in virt_vm.py keep calling the `remote_login` from aexpect.
https://github.com/avocado-framework/avocado-vt/blob/8d5fffe59920c5e844a3adb28655e9f6024fdd48/virttest/virt_vm.py#L1102

2021-04-28 11:50 UTC, pevogam commented
> How about my proposal in the related issue?

@yanan-fu, can you try/comment on my proposal too? I think the current PR might be an overkill to begin with.

2026-05-25 14:33 UTC, harvey0100 commented
Closing this PR due to current team constraints. This is part of a broader effort to triage all in-flight work across our upstream repos. If this work is still needed, please feel free to reopen and it will be picked up. Apologies for any inconvenience.

2026-05-25 14:34 UTC, closed without merging