Centos stream definitions
avocado-framework/avocado-vt pull request #3551
Opened 2022-10-25 12:34 UTC by richtja

This adds definitions and kickstart file to support tests on Centos stream.

Signed-off-by: Jan Richter <jarichte@redhat.com>

2022-10-26 11:29 UTC, luckyh approved these changes

2022-11-07 04:04 UTC, clebergnu requested changes
Hi @richtja ,

I've found two issues regarding resources (memory and image size).  Please take a look at them.

Thanks!

2022-11-07 04:04 UTC, clebergnu commented on virttest/shared/cfg/guest-os/Linux/CentOS-Stream/9.cfg
> +- 9:
For CentOS-Stream9, I'm getting an installation error: "Not enough space in file systems for the current software selection. An additional 1.71GiB is needed".

On the Avocado-VT side, it means having a larger `image_size` for this distro and corresponding KS file.  This works on my system:

```
avocado run --vt-guest-os Guest.Linux.CentOS-Stream.9.devel.x86_64 --vt-extra-params 'url=http://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/' --vt-extra-params 'image_size=15G' -- io-github-autotest-qemu.unattended_install.url.extra_cdrom_ks.default_install.aio_native
```

2023-02-07 16:22 UTC, richtja commented
Hi @luckyh and @clebergnu thanks for your reviews I created new version in #3617

2023-02-07 16:22 UTC, closed without merging